# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ventana_principal.ui'
##
## Created by: Qt User Interface Compiler version 6.10.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QMainWindow, QMdiArea, QMenu,
    QMenuBar, QSizePolicy, QStatusBar, QToolBar,
    QWidget)

class Ui_VentanaPrincipal(object):
    def setupUi(self, VentanaPrincipal):
        if not VentanaPrincipal.objectName():
            VentanaPrincipal.setObjectName(u"VentanaPrincipal")
        VentanaPrincipal.resize(783, 671)
        self.ac_basico = QAction(VentanaPrincipal)
        self.ac_basico.setObjectName(u"ac_basico")
        self.ac_cientifico = QAction(VentanaPrincipal)
        self.ac_cientifico.setObjectName(u"ac_cientifico")
        self.ac_conversor = QAction(VentanaPrincipal)
        self.ac_conversor.setObjectName(u"ac_conversor")
        self.ac_graficador = QAction(VentanaPrincipal)
        self.ac_graficador.setObjectName(u"ac_graficador")
        self.ac_salir = QAction(VentanaPrincipal)
        self.ac_salir.setObjectName(u"ac_salir")
        self.ac_oscuro = QAction(VentanaPrincipal)
        self.ac_oscuro.setObjectName(u"ac_oscuro")
        self.ac_claro = QAction(VentanaPrincipal)
        self.ac_claro.setObjectName(u"ac_claro")
        self.ac_alto_contraste = QAction(VentanaPrincipal)
        self.ac_alto_contraste.setObjectName(u"ac_alto_contraste")
        self.ac_cascade = QAction(VentanaPrincipal)
        self.ac_cascade.setObjectName(u"ac_cascade")
        self.ac_tile = QAction(VentanaPrincipal)
        self.ac_tile.setObjectName(u"ac_tile")
        self.ac_cerrar_todas = QAction(VentanaPrincipal)
        self.ac_cerrar_todas.setObjectName(u"ac_cerrar_todas")
        self.ac_borrar_historial = QAction(VentanaPrincipal)
        self.ac_borrar_historial.setObjectName(u"ac_borrar_historial")
        self.ac_acerca = QAction(VentanaPrincipal)
        self.ac_acerca.setObjectName(u"ac_acerca")
        self.tb_basico = QAction(VentanaPrincipal)
        self.tb_basico.setObjectName(u"tb_basico")
        self.tb_cientifico = QAction(VentanaPrincipal)
        self.tb_cientifico.setObjectName(u"tb_cientifico")
        self.tb_conversor = QAction(VentanaPrincipal)
        self.tb_conversor.setObjectName(u"tb_conversor")
        self.tb_graficador = QAction(VentanaPrincipal)
        self.tb_graficador.setObjectName(u"tb_graficador")
        self.tb_oscuro = QAction(VentanaPrincipal)
        self.tb_oscuro.setObjectName(u"tb_oscuro")
        self.tb_claro = QAction(VentanaPrincipal)
        self.tb_claro.setObjectName(u"tb_claro")
        self.tb_contraste = QAction(VentanaPrincipal)
        self.tb_contraste.setObjectName(u"tb_contraste")
        self.tb_mosaico = QAction(VentanaPrincipal)
        self.tb_mosaico.setObjectName(u"tb_mosaico")
        self.tb_cascada = QAction(VentanaPrincipal)
        self.tb_cascada.setObjectName(u"tb_cascada")
        self.centralwidget = QWidget(VentanaPrincipal)
        self.centralwidget.setObjectName(u"centralwidget")
        self.mdi_area = QMdiArea(self.centralwidget)
        self.mdi_area.setObjectName(u"mdi_area")
        self.mdi_area.setGeometry(QRect(9, 9, 711, 581))
        brush = QBrush(QColor(17, 8, 16, 255))
        brush.setStyle(Qt.BrushStyle.SolidPattern)
        self.mdi_area.setBackground(brush)
        self.mdi_area.setViewMode(QMdiArea.ViewMode.SubWindowView)
        VentanaPrincipal.setCentralWidget(self.centralwidget)
        self.menu_bar = QMenuBar(VentanaPrincipal)
        self.menu_bar.setObjectName(u"menu_bar")
        self.menu_bar.setGeometry(QRect(0, 0, 783, 33))
        self.menu_Calculadora = QMenu(self.menu_bar)
        self.menu_Calculadora.setObjectName(u"menu_Calculadora")
        self.menu_Vista = QMenu(self.menu_bar)
        self.menu_Vista.setObjectName(u"menu_Vista")
        self.menu_Ventanas_MDI = QMenu(self.menu_Vista)
        self.menu_Ventanas_MDI.setObjectName(u"menu_Ventanas_MDI")
        self.menu_Historial = QMenu(self.menu_bar)
        self.menu_Historial.setObjectName(u"menu_Historial")
        self.menu_Ayuda = QMenu(self.menu_bar)
        self.menu_Ayuda.setObjectName(u"menu_Ayuda")
        VentanaPrincipal.setMenuBar(self.menu_bar)
        self.toolbar = QToolBar(VentanaPrincipal)
        self.toolbar.setObjectName(u"toolbar")
        self.toolbar.setMovable(True)
        VentanaPrincipal.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.toolbar)
        self.status_bar = QStatusBar(VentanaPrincipal)
        self.status_bar.setObjectName(u"status_bar")
        VentanaPrincipal.setStatusBar(self.status_bar)

        self.menu_bar.addAction(self.menu_Calculadora.menuAction())
        self.menu_bar.addAction(self.menu_Vista.menuAction())
        self.menu_bar.addAction(self.menu_Historial.menuAction())
        self.menu_bar.addAction(self.menu_Ayuda.menuAction())
        self.menu_Calculadora.addAction(self.ac_basico)
        self.menu_Calculadora.addAction(self.ac_cientifico)
        self.menu_Calculadora.addAction(self.ac_conversor)
        self.menu_Calculadora.addAction(self.ac_graficador)
        self.menu_Calculadora.addSeparator()
        self.menu_Calculadora.addAction(self.ac_salir)
        self.menu_Vista.addAction(self.ac_oscuro)
        self.menu_Vista.addAction(self.ac_claro)
        self.menu_Vista.addAction(self.ac_alto_contraste)
        self.menu_Vista.addAction(self.menu_Ventanas_MDI.menuAction())
        self.menu_Ventanas_MDI.addAction(self.ac_cascade)
        self.menu_Ventanas_MDI.addAction(self.ac_tile)
        self.menu_Ventanas_MDI.addAction(self.ac_cerrar_todas)
        self.menu_Historial.addAction(self.ac_borrar_historial)
        self.menu_Ayuda.addAction(self.ac_acerca)
        self.toolbar.addAction(self.tb_basico)
        self.toolbar.addAction(self.tb_cientifico)
        self.toolbar.addAction(self.tb_conversor)
        self.toolbar.addAction(self.tb_graficador)
        self.toolbar.addAction(self.tb_oscuro)
        self.toolbar.addAction(self.tb_claro)
        self.toolbar.addAction(self.tb_contraste)
        self.toolbar.addAction(self.tb_mosaico)
        self.toolbar.addAction(self.tb_cascada)

        self.retranslateUi(VentanaPrincipal)

        QMetaObject.connectSlotsByName(VentanaPrincipal)
    # setupUi

    def retranslateUi(self, VentanaPrincipal):
        VentanaPrincipal.setWindowTitle(QCoreApplication.translate("VentanaPrincipal", u"Calculadora Cientifica Avanzada", None))
        self.ac_basico.setText(QCoreApplication.translate("VentanaPrincipal", u"Modo Basico", None))
#if QT_CONFIG(statustip)
        self.ac_basico.setStatusTip(QCoreApplication.translate("VentanaPrincipal", u"Calculadora basica aritmetica", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.ac_basico.setShortcut(QCoreApplication.translate("VentanaPrincipal", u"Ctrl+1", None))
#endif // QT_CONFIG(shortcut)
        self.ac_cientifico.setText(QCoreApplication.translate("VentanaPrincipal", u"Modo Cientifico", None))
#if QT_CONFIG(statustip)
        self.ac_cientifico.setStatusTip(QCoreApplication.translate("VentanaPrincipal", u"Calculadora con funciones cientificas", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.ac_cientifico.setShortcut(QCoreApplication.translate("VentanaPrincipal", u"Ctrl+2", None))
#endif // QT_CONFIG(shortcut)
        self.ac_conversor.setText(QCoreApplication.translate("VentanaPrincipal", u"Modo Conversor", None))
#if QT_CONFIG(statustip)
        self.ac_conversor.setStatusTip(QCoreApplication.translate("VentanaPrincipal", u"Convertidor de unidades", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.ac_conversor.setShortcut(QCoreApplication.translate("VentanaPrincipal", u"Ctrl+3", None))
#endif // QT_CONFIG(shortcut)
        self.ac_graficador.setText(QCoreApplication.translate("VentanaPrincipal", u"Modo Graficador", None))
#if QT_CONFIG(statustip)
        self.ac_graficador.setStatusTip(QCoreApplication.translate("VentanaPrincipal", u"Graficador de funciones matematicas", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.ac_graficador.setShortcut(QCoreApplication.translate("VentanaPrincipal", u"Ctrl+4", None))
#endif // QT_CONFIG(shortcut)
        self.ac_salir.setText(QCoreApplication.translate("VentanaPrincipal", u"Salir", None))
#if QT_CONFIG(shortcut)
        self.ac_salir.setShortcut(QCoreApplication.translate("VentanaPrincipal", u"Ctrl+Q", None))
#endif // QT_CONFIG(shortcut)
        self.ac_oscuro.setText(QCoreApplication.translate("VentanaPrincipal", u"Tema Oscuro", None))
#if QT_CONFIG(shortcut)
        self.ac_oscuro.setShortcut(QCoreApplication.translate("VentanaPrincipal", u"Ctrl+Shift+D", None))
#endif // QT_CONFIG(shortcut)
        self.ac_claro.setText(QCoreApplication.translate("VentanaPrincipal", u"Tema Claro", None))
#if QT_CONFIG(shortcut)
        self.ac_claro.setShortcut(QCoreApplication.translate("VentanaPrincipal", u"Ctrl+Shift+L", None))
#endif // QT_CONFIG(shortcut)
        self.ac_alto_contraste.setText(QCoreApplication.translate("VentanaPrincipal", u"Alto Contraste", None))
#if QT_CONFIG(shortcut)
        self.ac_alto_contraste.setShortcut(QCoreApplication.translate("VentanaPrincipal", u"Ctrl+Shift+A", None))
#endif // QT_CONFIG(shortcut)
        self.ac_cascade.setText(QCoreApplication.translate("VentanaPrincipal", u"Cascada", None))
#if QT_CONFIG(shortcut)
        self.ac_cascade.setShortcut(QCoreApplication.translate("VentanaPrincipal", u"Ctrl+Shift+C", None))
#endif // QT_CONFIG(shortcut)
        self.ac_tile.setText(QCoreApplication.translate("VentanaPrincipal", u"Mosaico", None))
#if QT_CONFIG(shortcut)
        self.ac_tile.setShortcut(QCoreApplication.translate("VentanaPrincipal", u"Ctrl+Shift+T", None))
#endif // QT_CONFIG(shortcut)
        self.ac_cerrar_todas.setText(QCoreApplication.translate("VentanaPrincipal", u"Cerrar todas", None))
#if QT_CONFIG(shortcut)
        self.ac_cerrar_todas.setShortcut(QCoreApplication.translate("VentanaPrincipal", u"Ctrl+Shift+W", None))
#endif // QT_CONFIG(shortcut)
        self.ac_borrar_historial.setText(QCoreApplication.translate("VentanaPrincipal", u"Borrar historial", None))
#if QT_CONFIG(shortcut)
        self.ac_borrar_historial.setShortcut(QCoreApplication.translate("VentanaPrincipal", u"Ctrl+H", None))
#endif // QT_CONFIG(shortcut)
        self.ac_acerca.setText(QCoreApplication.translate("VentanaPrincipal", u"Acerca de...", None))
#if QT_CONFIG(shortcut)
        self.ac_acerca.setShortcut(QCoreApplication.translate("VentanaPrincipal", u"F1", None))
#endif // QT_CONFIG(shortcut)
        self.tb_basico.setText(QCoreApplication.translate("VentanaPrincipal", u"Basico", None))
        self.tb_cientifico.setText(QCoreApplication.translate("VentanaPrincipal", u"Cientifico", None))
        self.tb_conversor.setText(QCoreApplication.translate("VentanaPrincipal", u"Conversor", None))
        self.tb_graficador.setText(QCoreApplication.translate("VentanaPrincipal", u"Graficador", None))
        self.tb_oscuro.setText(QCoreApplication.translate("VentanaPrincipal", u"Oscuro", None))
        self.tb_claro.setText(QCoreApplication.translate("VentanaPrincipal", u"Claro", None))
        self.tb_contraste.setText(QCoreApplication.translate("VentanaPrincipal", u"Contraste", None))
        self.tb_mosaico.setText(QCoreApplication.translate("VentanaPrincipal", u"Mosaico", None))
        self.tb_cascada.setText(QCoreApplication.translate("VentanaPrincipal", u"Cascada", None))
        self.menu_Calculadora.setTitle(QCoreApplication.translate("VentanaPrincipal", u"&Calculadora", None))
        self.menu_Vista.setTitle(QCoreApplication.translate("VentanaPrincipal", u"&Vista", None))
        self.menu_Ventanas_MDI.setTitle(QCoreApplication.translate("VentanaPrincipal", u"&Ventanas MDI", None))
        self.menu_Historial.setTitle(QCoreApplication.translate("VentanaPrincipal", u"&Historial", None))
        self.menu_Ayuda.setTitle(QCoreApplication.translate("VentanaPrincipal", u"A&yuda", None))
        self.toolbar.setWindowTitle(QCoreApplication.translate("VentanaPrincipal", u"Principal", None))
    # retranslateUi

